### ISSUE TITLE
No block storage pvc found or not supported yet

### ISSUE THREAD

**Issue by saingithub** [kais271/pvc-exporter#20]
In my kubernetes environment Dell CSI driver is the storage provisioner. When I implemented this PV-exporter I am getting the following error in the logs
No block storage pvc found or not supported yet

**Comment by kais271** [comment]
> In my kubernetes environment Dell CSI driver is the storage provisioner. When I implemented this PV-exporter I am getting the following error in the logs No block storage pvc found or not supported yet

@saingithub Could you please share the result for "df -h" ?  and tell me which version you using.

**Comment by saingithub** [comment]
Thanks, @kais271, It worked for me. Could you please let me know how can I add it in Grafana Dashboard

**Comment by kais271** [comment]
@saingithub which version is you using ? If you using v0.1.2, you can try use this query "(sum without (container,pod,service,namespace,job,instance,endpoint) (pvc_usage)) + on(volumename) group_left(persistentvolumeclaim,mountedby,pod_namespace)pvc_mapping*0 "

**Comment by saingithub** [comment]
The version i am using is v7.1.5. When I give that query I am getting the following error.

"invalid expression type \"string\" for range query, must be Scalar or instant Vector"

**Comment by kais271** [comment]
> The version i am using is v7.1.5. When I give that query I am getting the following error.
> 
> "invalid expression type "string" for range query, must be Scalar or instant Vector"

don't have "" ..just **(sum without (container,pod,service,namespace,job,instance,endpoint) (pvc_usage)) + on(volumename) group_left(persistentvolumeclaim,mountedby,pod_namespace)pvc_mapping*0**

**Comment by saingithub** [comment]
"many-to-many matching not allowed: matching labels must be unique on one side"

**Comment by kais271** [comment]
could you please share the full error? and check whether they have the same **"job"**

**Comment by saingithub** [comment]
Is there is any option to get it in a tabular format in Grafana

**Comment by kais271** [comment]
Sorry, I don't  know

**Comment by saingithub** [comment]
I tried deploying v0.1.3-alpha version. I am getting the following error in the pod log

File "./pvc-exporter.py", line 9, in <module>
EXPORTER_SERVER_PORT=int(os.getenv('EXPORTER_SERVER_PORT'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by kais271** [comment]
you can check if the yaml of the pod has an EXPORTER_SERVER_PORT variable

**Comment by saingithub** [comment]
I had used the yaml file of v0.1.2 for the deployment of the pod.

**Comment by kais271** [comment]
that's not work.  you need use v0.1.3-alpha chart to install v0.1.3-alpha. because it has more changes.

**Comment by saingithub** [comment]
In v0.1.3 you have now created deployment files in which lots of variables are used compared to the previous version. How can I interpret that to deploy in a Kubernetes environment

**Comment by kais271** [comment]
@saingithub There are 3 variables: HOST_IP,EXPORTER_SERVER_PORT,SCAN_INTERVAL.
HOST_IP: This used to match pv. We get all pv via API, and deploy pvc-exporter as daemonset. So the pod only get the pv size of hostpath pv on current the node. 
EXPORTER_SERVER_PORT: This is exporter http server port in pod.
SCAN_INTERVAL: This is scan pvc interval, unit is second.

**Comment by saingithub** [comment]
![grafana](https://user-images.githubusercontent.com/68419313/143191558-83ad59a7-bf6f-4e64-9e50-09bd8647789b.png)

I have more than 100 PVC. I have attached the grafana dashboard image. Is there any way to filter it more so that we can interpret it easy.

**Comment by kais271** [comment]
@saingithub You can try this dashsboard. It can filter by namespace or pod.
https://github.com/kais271/pvc-exporter/blob/v0.1.3-alpha/docs/PVC%20%20Dashboard-1637745492005.json

![image](https://user-images.githubusercontent.com/19722587/143210331-999c27fc-2f27-4d17-bcf0-6e4f5569d5b1.png)

**Comment by saingithub** [comment]
When I used the above file I am getting the following error in Grafana

Panel plugin not found: timeseries

**Comment by kais271** [comment]
Maybe caused by grafana version. My version is v8.1.2 . Try the following steps 
1. 
`(sum without (container,pod,service,namespace,job,instance,endpoint,pvc_namespace,pvc_requested_size_MB) (pvc_usage)) + on(persistentvolume) group_left(persistentvolumeclaim,mountedby,pod_namespace)pvc_mapping{pod_namespace=~"$pod_namespace",mountedby=~"$Pod"}*0`
![image](https://user-images.githubusercontent.com/19722587/143247396-1e08548c-8a53-498a-8809-4ffb8420752f.png)
**2.**
![image](https://user-images.githubusercontent.com/19722587/143247522-4ea90134-4651-4793-9196-50429e1133c8.png)
**3.**
![image](https://user-images.githubusercontent.com/19722587/143247660-8fd77ef9-e1cd-4411-8ff9-5a3c3893d91c.png)

**Comment by saingithub** [comment]
When i give the above expression no data is getting in the dashboard
![grafana1](https://user-images.githubusercontent.com/68419313/143527467-23dca656-8233-4000-b683-46a56f72b54b.png)

**Comment by saingithub** [comment]
Hi,
Thanks, @kais271.
 
It worked for me. Now I was able to differentiate PVC usage by namespace and pods.

One more thing , is there any way to create an alert mechanism if any PVC exceeds a specified limit

**Comment by kais271** [comment]
@saingithub You can reference this: https://grafana.com/docs/grafana/latest/alerting/old-alerting/create-alerts/
But "Template variables are not supported in alert queries", so you need to create a new dashboard for alert.

**Comment by kais271** [comment]
Issues close after 30d of inactivity.
Reopen the issue with /reopen.
