### ISSUE TITLE
Error when using the expression in Prometheus

### ISSUE THREAD

**Issue by joshkurian** [kais271/pvc-exporter#21]
Team,
In the Prometheus when I am giving the expression: (sum without (container,pod,service,namespace,job,instance,endpoint) (pvc_usage)) + on(volumename) group_left(persistentvolumeclaim,mountedby,pod_namespace)pvc_mapping*0. I am getting the following error. Please let me know if you need to make any changes to the application.
Error executing query: found duplicate series for the match group {volumename="dc-dev-test-cluster-73e96a4ca5"} on the right hand-side of the operation: [{endpoint="metrics", instance="10.20.41.118:8849", job="pod-pvc-mapping", mountedby="prometheus-rancher-monitoring-prometheus-0", namespace="pvc-exporter", persistentvolumeclaim="prometheus-rancher-monitoring-prometheus-db-prometheus-rancher-monitoring-prometheus-0", pod="pod-pvc-mapping-7f68cc69c5-29bzz", pod_namespace="cattle-monitoring-system", service="pod-pvc-mapping", volumename="dc-dev-test-cluster-73e96a4ca5"}, {endpoint="metrics", instance="10.20.41.118:8849", job="pvc-exporter", mountedby="prometheus-rancher-monitoring-prometheus-0", namespace="pvc-exporter", persistentvolumeclaim="prometheus-rancher-monitoring-prometheus-db-prometheus-rancher-monitoring-prometheus-0", pod="pod-pvc-mapping-7f68cc69c5-29bzz", pod_namespace="cattle-monitoring-system", service="pod-pvc-mapping", volumename="dc-dev-test-cluster-73e96a4ca5"}];many-to-many matching not allowed: matching labels must be unique on one side

**Comment by kais271** [comment]
> Error executing query: found duplicate series for the match group {volumename="dc-dev-test-cluster-73e96a4ca5"} on the right hand-side of the operation: [{endpoint="metrics", instance="10.20.41.118:8849", **job="pod-pvc-mapping",** mountedby="prometheus-rancher-monitoring-prometheus-0", namespace="pvc-exporter", persistentvolumeclaim="prometheus-rancher-monitoring-prometheus-db-prometheus-rancher-monitoring-prometheus-0", pod="pod-pvc-mapping-7f68cc69c5-29bzz", pod_namespace="cattle-monitoring-system", service="pod-pvc-mapping", volumename="dc-dev-test-cluster-73e96a4ca5"}, {endpoint="metrics", instance="10.20.41.118:8849", **job="pvc-exporter",** mountedby="prometheus-rancher-monitoring-prometheus-0", namespace="pvc-exporter", persistentvolumeclaim="prometheus-rancher-monitoring-prometheus-db-prometheus-rancher-monitoring-prometheus-0", pod="pod-pvc-mapping-7f68cc69c5-29bzz", pod_namespace="cattle-monitoring-system", service="pod-pvc-mapping", volumename="dc-dev-test-cluster-73e96a4ca5"}];many-to-many matching not allowed: matching labels must be unique on one side

Hi, which version is you using ? I see 2 job provide this metric. Suppose you upgrade or reinstall, you can try to shorten the time range .
![image](https://user-images.githubusercontent.com/19722587/139518173-80530790-7fd3-4a02-bdd6-87bfceebb9d7.png)

**Comment by joshkurian** [comment]
Thank you for the response. 

2 Service monitors were created unknowingly. Deleted of them and expression is working now.

**Comment by kais271** [comment]
Issues close after 30d of inactivity.
Reopen the issue with /reopen.
