### ISSUE TITLE
ASK alicloud can't use, because there is no concept of node. 阿里云ASK里无法使用，因为没有节点概念。

### ISSUE THREAD

**Issue by Spinestars** [kais271/pvc-exporter#25]
I saw, in the helm of the configuration, the pv - exporter hostpath to mount the root node to the/host.
But cannot support hostpath aliyun - ask way.
Hi, if I can make the program has side car container to deploy, and to mount NFS PVC/host, so as to get a mount information and calculate the storage size?
---
我看到，在helm里的配置中，pv-exporter 通过hostpath来挂载节点根到/host上。
但aliyun-ask无法支撑hostpath方式。

Hi，我是否可以将程序已边车容器的方式来部署，并将nfs pvc挂载到/host上，从而拿到挂载信息并计算存储大小？

**Comment by kais271** [comment]
没有节点概念的话还有hostpath类型的pvc吗？
理论上将变量都配好，nfs pvc挂到/host，以sidecar的形式应该是能解析nfs pvc的。

**Comment by kais271** [comment]
Issues close after 30d of inactivity.
Reopen the issue with /reopen.
