### ISSUE TITLE
pvc-exporter crash when pod is deleted 

### ISSUE THREAD

**Issue by ComeBurguburu** [kais271/pvc-exporter#28]
pvc-exporter crash when deleting a pod (my pod was created by a job)

````
File "//./pvc-exporter.py", line 169, in <module>
--
Thu, Apr 21 2022 3:17:12 pm | pod_status=k8s_api_obj.read_namespaced_pod(pod_name,ns).status
Thu, Apr 21 2022 3:17:12 pm | File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 22990, in read_namespaced_pod
Thu, Apr 21 2022 3:17:12 pm | return self.read_namespaced_pod_with_http_info(name, namespace, **kwargs) # noqa: E501
Thu, Apr 21 2022 3:17:12 pm | File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 23085, in read_namespaced_pod_with_http_info
Thu, Apr 21 2022 3:17:12 pm | return self.api_client.call_api(
Thu, Apr 21 2022 3:17:12 pm | File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
Thu, Apr 21 2022 3:17:12 pm | return self.__call_api(resource_path, method,
Thu, Apr 21 2022 3:17:12 pm | File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
Thu, Apr 21 2022 3:17:12 pm | response_data = self.request(
Thu, Apr 21 2022 3:17:12 pm | File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 373, in request
Thu, Apr 21 2022 3:17:12 pm | return self.rest_client.GET(url,
Thu, Apr 21 2022 3:17:12 pm | File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 240, in GET
Thu, Apr 21 2022 3:17:12 pm | return self.request("GET", url,
Thu, Apr 21 2022 3:17:12 pm | File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 234, in request
Thu, Apr 21 2022 3:17:12 pm | raise ApiException(http_resp=r)
Thu, Apr 21 2022 3:17:12 pm | kubernetes.client.exceptions.ApiException: (404)
Thu, Apr 21 2022 3:17:12 pm | Reason: Not Found
Thu, Apr 21 2022 3:17:12 pm | HTTP response headers: HTTPHeaderDict({'Audit-Id': '38a98825-6494-4367-865b-241f91cc2809', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '3c02572f-e040-4488-ab28-adcffa964861', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'b3f7639f-2433-4ddb-94c0-11f8072aa518', 'Date': 'Thu, 21 Apr 2022 13:17:12 GMT', 'Content-Length': '290'})
Thu, Apr 21 2022 3:17:12 pm | HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"my-pod-name\" not found","reason":"NotFound","details":{"name":"my-pod-name","kind":"pods"},"code":404}
````

**Comment by kais271** [comment]
ok, give me some times to repro this issue.

在 2022年4月21日，21:24，CômeBurguburu ***@***.***> 写道：

﻿

pvc-exporter crash when deleting a pod (my pod was created by a job)

File "//./pvc-exporter.py", line 169, in <module>
--
Thu, Apr 21 2022 3:17:12 pm | pod_status=k8s_api_obj.read_namespaced_pod(pod_name,ns).status
Thu, Apr 21 2022 3:17:12 pm | File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 22990, in read_namespaced_pod
Thu, Apr 21 2022 3:17:12 pm | return self.read_namespaced_pod_with_http_info(name, namespace, **kwargs) # noqa: E501
Thu, Apr 21 2022 3:17:12 pm | File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 23085, in read_namespaced_pod_with_http_info
Thu, Apr 21 2022 3:17:12 pm | return self.api_client.call_api(
Thu, Apr 21 2022 3:17:12 pm | File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
Thu, Apr 21 2022 3:17:12 pm | return self.__call_api(resource_path, method,
Thu, Apr 21 2022 3:17:12 pm | File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
Thu, Apr 21 2022 3:17:12 pm | response_data = self.request(
Thu, Apr 21 2022 3:17:12 pm | File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 373, in request
Thu, Apr 21 2022 3:17:12 pm | return self.rest_client.GET(url,
Thu, Apr 21 2022 3:17:12 pm | File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 240, in GET
Thu, Apr 21 2022 3:17:12 pm | return self.request("GET", url,
Thu, Apr 21 2022 3:17:12 pm | File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 234, in request
Thu, Apr 21 2022 3:17:12 pm | raise ApiException(http_resp=r)
Thu, Apr 21 2022 3:17:12 pm | kubernetes.client.exceptions.ApiException: (404)
Thu, Apr 21 2022 3:17:12 pm | Reason: Not Found
Thu, Apr 21 2022 3:17:12 pm | HTTP response headers: HTTPHeaderDict({'Audit-Id': '38a98825-6494-4367-865b-241f91cc2809', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '3c02572f-e040-4488-ab28-adcffa964861', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'b3f7639f-2433-4ddb-94c0-11f8072aa518', 'Date': 'Thu, 21 Apr 2022 13:17:12 GMT', 'Content-Length': '290'})
Thu, Apr 21 2022 3:17:12 pm | HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"my-pod-name\" not found","reason":"NotFound","details":{"name":"my-pod-name","kind":"pods"},"code":404}

**Comment by kais271** [comment]
@ComeBurguburu 
Hi, you can try this image: dockerid31415926/pvc-exporter:v0.1.4-alpha.x86

**Comment by ComeBurguburu** [comment]
It seem better, the error is show but the exporter doesn't crash, the fix work as expected:
But there are still this code's error: UnboundLocalError: local variable 'fs_path' referenced before assignment


````
Traceback (most recent call last):
--
Tue, Apr 26 2022 3:53:07 pm | File "//./pvc-exporter.py", line 192, in <module>
Tue, Apr 26 2022 3:53:07 pm | pvc_used_MB,pvc_used_percent,pvc_type=get_pvc_used(pv_info,pvc_requested_size_MB)
Tue, Apr 26 2022 3:53:07 pm | File "//./pvc-exporter.py", line 103, in get_pvc_used
Tue, Apr 26 2022 3:53:07 pm | pvc_used,pvc_used_percent=calculate_size(fs_path,total_MB_size,pvc_type)
Tue, Apr 26 2022 3:53:07 pm | UnboundLocalError: local variable 'fs_path' referenced before assignment
Tue, Apr 26 2022 3:53:08 pm | 2022-04-26 13:53:08,115 - pvc-exporter - ERROR - Cannot resolve the spec for this pod: studio-75454c7d64-8bpz5

**Comment by kais271** [comment]
This is only a temporary fix, I will handle this exception in release v0.1.4-beta, and I will notify you when the time comes.

**Comment by kais271** [comment]
Issues close after 30d of inactivity.
Reopen the issue with /reopen.
