### ISSUE TITLE
Doesn't work in gcloud

### ISSUE THREAD

**Issue by korjavin** [kais271/pvc-exporter#3]
```
curl 127.0.0.1:8848/metrics
# HELP python_gc_objects_collected_total Objects collected during gc
# TYPE python_gc_objects_collected_total counter
python_gc_objects_collected_total{generation="0"} 340.0
python_gc_objects_collected_total{generation="1"} 33.0
python_gc_objects_collected_total{generation="2"} 0.0
# HELP python_gc_objects_uncollectable_total Uncollectable object found during GC
# TYPE python_gc_objects_uncollectable_total counter
python_gc_objects_uncollectable_total{generation="0"} 0.0
python_gc_objects_uncollectable_total{generation="1"} 0.0
python_gc_objects_uncollectable_total{generation="2"} 0.0
# HELP python_gc_collections_total Number of times this generation was collected
# TYPE python_gc_collections_total counter
python_gc_collections_total{generation="0"} 35.0
python_gc_collections_total{generation="1"} 3.0
python_gc_collections_total{generation="2"} 0.0
# HELP python_info Python platform information
# TYPE python_info gauge
python_info{implementation="CPython",major="3",minor="8",patchlevel="7",version="3.8.7"} 1.0
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 1.77471488e+08
# HELP process_resident_memory_bytes Resident memory size in bytes.
# TYPE process_resident_memory_bytes gauge
process_resident_memory_bytes 1.9795968e+07
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1.61505511176e+09
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 0.32
# HELP process_open_fds Number of open file descriptors.
# TYPE process_open_fds gauge
process_open_fds 7.0
# HELP process_max_fds Maximum number of open file descriptors.
# TYPE process_max_fds gauge
process_max_fds 1.048576e+06
# HELP pvc_usage fetching usge matched by k8s csi
# TYPE pvc_usage gauge
```

**Comment by kais271** [comment]
Hi ， could you  please run 'df -h' on your hosts and share the results?

**Comment by korjavin** [comment]
```
There are too many lines, but I guess this one is about PVC
/dev/sdf        8.4G   47M  8.4G   1% /var/lib/kubelet/plugins/kubernetes.io/gce-pd/mounts/gke-data-bd2c320a-dyna-pvc-41e03eb9-503e-11eb-8f2d-42010a8001bd

```

**Comment by kais271** [comment]
Hi , please try this version "dockerid31415926/block-pvc-scanner:beta-v0.1.1",you can pulling that from docker hub
or build it from brache 'beta-v0.1.1'.

**Comment by korjavin** [comment]
It's getting better.

In block scanner i've got some values:
```
curl localhost:8848/metrics
pvc_usage{volumename="gke-data-bd2c320a-dyna-pvc-6b0f9f4c-8d42-11ea-bc86-42010a80019b\n"} 0.01
pvc_usage{volumename="gke-data-bd2c320a-dyna-pvc-88516e02-9ae2-11ea-9512-42010a8000f0\n"} 0.01
pvc_usage{volumename="gke-data-bd2c320a-dyna-pvc-9c96e158-0638-11eb-ac6a-42010a80000e\n"} 0.14
pvc_usage{volumename="gke-data-bd2c320a-dyna-pvc-9c97c32f-0638-11eb-ac6a-42010a80000e\n"} 0.01
```

But pvc_mapping is still empty ;(

**Comment by korjavin** [comment]
Logs from pvc-mapping pod contains this:
```
PVC: data-redis-redis-ha-server-1, VOLUME: pvc-1dcd062b-bb2a-11ea-9512-42010a8000f0, POD: redis-redis-ha-server-1
PVC: data-redis-redis-ha-server-2, VOLUME: pvc-299ea6c3-bb2a-11ea-9512-42010a8000f0, POD: redis-redis-ha-server-2
```

**Comment by korjavin** [comment]
I think I found problem of scrapping. I'm trying to fix this now.

**Comment by korjavin** [comment]
Both metrics exist now.
![image](https://user-images.githubusercontent.com/148765/110309856-e97d4600-8012-11eb-8053-07bf8bd4c274.png)


Problem is in this query now
![image](https://user-images.githubusercontent.com/148765/110309960-074aab00-8013-11eb-9d13-818c7852bb32.png)

**Comment by kais271** [comment]
This caused by volumename not match between pvc_usage and pvc_mapping. I have updated the code for block-pvc-scanner, you can download the image "dockerid31415926/block-pvc-scanner:beta-v0.1.1" again or build it from brache 'beta-v0.1.1'.

**Comment by korjavin** [comment]
I updated image in the container.

What I see now (limited to one volume)
```
pvc_mapping -> pvc-41553461-503e-11eb-8f2d-42010a8001bd

pvc_usage ->  pvc-41553461-503e-11eb-8f2d-42010a8001bd

```

seems they are the same.
But still I have an empty graph.

May be your prometheus is different

**Comment by kais271** [comment]
You can try to split this query as following then running separately. I don't have test env now, so I can't verify it.
1.(sum without (pod,service,namespace,job,instance,endpoint) (pvc_usage)) 2.group_left(persistentvolumeclaim,mountedby)pvc_mapping*0

**Comment by andikercuku** [comment]
Hi kais271,

What about: /var/lib/kubelet/plugins/kubernetes.io/flexvolume/oracle/oci/mounts/ocid1.volume.oc1.eu-frankfurt-1.
How should be the scanner.py, specially the line 14  _elif re.match_ ? Will this work when pvc_usage ?

Thank you.

**Comment by kais271** [comment]
> Hi kais271,
> 
> What about: /var/lib/kubelet/plugins/kubernetes.io/flexvolume/oracle/oci/mounts/ocid1.volume.oc1.eu-frankfurt-1.
> How should be the scanner.py, specially the line 14 _elif re.match_ ? Will this work when pvc_usage ?
> 
> Thank you.

**Comment by kais271** [comment]
@andikercuku  The rex is used to get below data.
![image](https://user-images.githubusercontent.com/19722587/123813861-d1199a00-d927-11eb-8571-a3816167a4ce.png)

**Comment by andikercuku** [comment]
yes understand, so the get_pvc=os.popen("df -h|grep -E 'kubernetes.io/flexvolume|kubernetes.io~csi|kubernetes.io/flexvolume/oracle/oci/mounts'") and elif re.match("^ocid1.volume.oc1.eu-frankfurt-1",v): 
 Is this ok ?

**Comment by kais271** [comment]
> yes understand, so the get_pvc=os.popen("df -h|grep -E 'kubernetes.io/flexvolume|kubernetes.io~csi|kubernetes.io/flexvolume/oracle/oci/mounts'") and elif re.match("^ocid1.volume.oc1.eu-frankfurt-1",v):
> Is this ok ?

@andikercuku I think it will be ok. or, just  **re.match("^ocid",v)**.

**Comment by andik101** [comment]
Hi kais271,
What about pod crash with this error:

`File "./pod-pvc-mapping.py", line 23, in <module>
    for vc in p['spec']['volumes']:
TypeError: 'NoneType' object is not iterable`

**Comment by kais271** [comment]
> Hi kais271,
> What about pod crash with this error:
> 
> `File "./pod-pvc-mapping.py", line 23, in <module> for vc in p['spec']['volumes']: TypeError: 'NoneType' object is not iterable`

@andik101 I think it's cased by no data in p['spec']['volumes'],you can add a 'print(p)' to debug, like below.
![image](https://user-images.githubusercontent.com/19722587/124210715-831ab700-db1e-11eb-98a8-4922e685461d.png)
