### ISSUE TITLE
promethues里查不到数据，提示No datapoints found.

### ISSUE THREAD

**Issue by bill-ding007** [kais271/pvc-exporter#30]
配置了service的annotations也一样
service:
    headless: false
    type: ClusterIP
    port: 8848
    labels: {}
  annotations:
      prometheus.io/port: "8848"
      prometheus.io/scrape: "true"
      prometheus.io/scheme: http
      daocloud.io/component: pvc-exporter
      service.daocloud.io/scrape: 'false'

**Comment by kais271** [comment]
Prometheus的targets里有pvc-exporter吗？如果有的话你可以看下主机的时间跟客户端是否匹配
***@***.***


发件人: ***@***.***>
发送时间: 2022年4月25日 17:06
收件人: ***@***.***>
抄送: ***@***.***>
主题: [kais271/pvc-exporter] promethues里查不到数据，提示No datapoints found. (Issue #30)


配置了service的annotations也一样
service:
headless: false
type: ClusterIP
port: 8848
labels: {}
annotations:
prometheus.io/port: "8848"
prometheus.io/scrape: "true"
prometheus.io/scheme: http
daocloud.io/component: pvc-exporter
service.daocloud.io/scrape: 'false'

―

**Comment by bill-ding007** [comment]
targets里没有pvc-exporter

**Comment by kais271** [comment]
直接charts部署的，values都是默认的吗？
另外看下prometheus的配置，关注下面的部分。kubectl  get prometheus -A -o yaml
***@***.***

发件人: ***@***.***>
发送时间: 2022年4月25日 17:34
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [kais271/pvc-exporter] promethues里查不到数据，提示No datapoints found. (Issue #30)


targets里没有pvc-exporter

―

**Comment by kais271** [comment]
Issues close after 30d of inactivity.
Reopen the issue with /reopen.
