### ISSUE TITLE
Unable to add PVC exporter as a target to Prometheus Server

### ISSUE THREAD

**Issue by Nambivert** [kais271/pvc-exporter#31]
Hi,

I have been trying to use PVC exporter in my GKE cluster where Prometheus and Grafana are running in different namespaces in LBs

Prometheus: http://35.239.240.86/
Grafana: http://34.121.115.148/ (admin:admin)
PVC Exporter: http://35.193.205.38:8848/

But I am unable to see any metrics of PVC usage in my prometheus server. Can you please help me resolving this issue? Thanks!

**Comment by Nambivert** [comment]
I have fixed the issue from my end and the reason being not adding Prometheus target in ConfigMap. The solution works perfect. Thanks for contributing.

**Comment by kais271** [comment]
Great to hear this, thank you for your support.
