### ISSUE TITLE
pvc被删除后metrics还在

### ISSUE THREAD

**Issue by sysadminxxx** [kais271/pvc-exporter#32]
如题，能把已删除的pvc移除吗？
另外，round只取2位，以及amend加0.01太多了吧，失真太多，要么直接输出pvc_used_MB和pvc_requested_size_MB

**Comment by kais271** [comment]
收到，最近比较忙，晚点看一下。

在 2022年6月1日，17:47，sysrootxyz ***@***.***> 写道：

﻿

如题，能把已删除的pvc移除吗？
另外，round只取2位，以及amend加0.01太多了吧，失真太多，要么直接输出pvc_used_MB和pvc_requested_size_MB

**Comment by kais271** [comment]
Issues close after 30d of inactivity.
Reopen the issue with /reopen.
