### ISSUE TITLE
upload the helm chart to a helm repo

### ISSUE THREAD

**Issue by balihb** [kais271/pvc-exporter#8]
It is possible to consume the helm chart from the git repo, but it would be way easier if it would be in a helm repository.

**Comment by kais271** [comment]
Hi , you can try this. 
helm repo add pvc-exporter https://kais271.github.io/pvc-exporter/helm3/charts/

**Comment by balihb** [comment]
can you also include the namespace change? :)

**Comment by balihb** [comment]
it is working

**Comment by kais271** [comment]
I have merged your changes.  And packaged a new charts as v0.1.1-fix

**Comment by balihb** [comment]
works great! thanks!
